name: Build & Publish Release APK

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  changelog:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate a complete changelog for repo
      uses: orhun/git-cliff-action@v3
      with:
        config: cliff.toml
        args: --verbose
      env:
        OUTPUT: CHANGELOG.md

    - name: Generate a changelog for f-droid
      uses: orhun/git-cliff-action@v3
      id: git-cliff
      with:
        config: cliff.toml
        args: -vv --latest --strip header
      env:
        OUTPUT: fastlane/metadata/android/en-US/changelogs/${{ steps.vars.outputs.tag }}.md

    - name: Commit
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        set +e
        git add --all
        git commit -m "Update changelog"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git main


  build:
    runs-on: ubuntu-latest
    needs: changelog
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
    - name: Make Gradle executable
      run: chmod +x gradlew

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}

    - name: Bump version
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle # or app/build.gradle.kts
        versionCode: ${{github.run_number}}
        versionName: ${{env.RELEASE_VERSION}}

    - name: Build APK
      # run: ./gradlew assembleDebug
      run: ./gradlew build

    - name: Upload artifact Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/release/*.apk

    # - name: Build apk
      # run: ./gradlew build
    # - name: Sign apk
      # uses: r0adkll/sign-android-release@v1
      # id: sign_app # ID used to access action output
      # with:
        # releaseDirectory: app/build/outputs/apk/release
        # signingKeyBase64: ${{ secrets.KEY_STORE }}
        # alias: ${{ secrets.ALIAS }}
        # keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        # keyPassword: ${{ secrets.KEY_PASSWORD }}

    # - name: Release to GitHub
      # uses: svenstaro/upload-release-action@v2
      # with:
        # repo_token: ${{ secrets.GITHUB_TOKEN }}
        # file: ${{steps.sign_app.outputs.signedReleaseFile}}
        # asset_name: OlauncherCF-${{ github.ref_name }}.apk
        # tag: ${{ github.ref }}
        # overwrite: true
        # body: "OlauncherCF.apk Release"
  release:
    permissions:
      contents: write
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: github-action-release-apk
        uses: gogoadl/github-action-release-apk@v1.0.0-alpha09
        with:
          asset-name: 'OlauncherCF.apk'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base64-keystore: ${{ secrets.KEY_STORE_BASE64 }}
          key-file: ${{ secrets.KEY_STORE }}
          keystore-password: ${{ secrets.KEY_STORE_PASSWORD }}
          keystore-alias: ${{ secrets.ALIAS }}
          key-password: ${{ secrets.KEY_PASSWORD }}
